// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN5BZ80Lt-GLdPMjM2zveHU7geWtXgxFM',
    appId: '1:305708010940:web:2fb7f195aabd4f13546fb9',
    messagingSenderId: '305708010940',
    projectId: 'press-wave',
    authDomain: 'press-wave.firebaseapp.com',
    storageBucket: 'press-wave.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEVrLk2nDTLXFQqqB8PRv1YDIg-lSI00o',
    appId: '1:305708010940:android:f4e67dd8e1976b41546fb9',
    messagingSenderId: '305708010940',
    projectId: 'press-wave',
    storageBucket: 'press-wave.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYt8kOyhjZLyDYO9qKTS9RpLVK5WTbZ4s',
    appId: '1:305708010940:ios:ac4553da7602716b546fb9',
    messagingSenderId: '305708010940',
    projectId: 'press-wave',
    storageBucket: 'press-wave.appspot.com',
    iosBundleId: 'com.example.pressWave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYt8kOyhjZLyDYO9qKTS9RpLVK5WTbZ4s',
    appId: '1:305708010940:ios:ac4553da7602716b546fb9',
    messagingSenderId: '305708010940',
    projectId: 'press-wave',
    storageBucket: 'press-wave.appspot.com',
    iosBundleId: 'com.example.pressWave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN5BZ80Lt-GLdPMjM2zveHU7geWtXgxFM',
    appId: '1:305708010940:web:5ff2d34c966014b8546fb9',
    messagingSenderId: '305708010940',
    projectId: 'press-wave',
    authDomain: 'press-wave.firebaseapp.com',
    storageBucket: 'press-wave.appspot.com',
  );

}