// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZad41IxaykVFhgVXWr8AciOXDIHuQccU',
    appId: '1:572486055461:web:5518744b2a549c455c71cc',
    messagingSenderId: '572486055461',
    projectId: 'presswave',
    authDomain: 'presswave.firebaseapp.com',
    storageBucket: 'presswave.appspot.com',
    measurementId: 'G-VRQ01CCJVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ6kmkFZXSYHfF9W_HcwQ42VEDxRPI_XM',
    appId: '1:572486055461:android:c2289ab81d1af7205c71cc',
    messagingSenderId: '572486055461',
    projectId: 'presswave',
    storageBucket: 'presswave.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9xa_seqwl3wdMqlAVFf1pEzqAbA2SQ2c',
    appId: '1:572486055461:ios:b44292202a9968575c71cc',
    messagingSenderId: '572486055461',
    projectId: 'presswave',
    storageBucket: 'presswave.appspot.com',
    iosBundleId: 'com.example.pressWave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9xa_seqwl3wdMqlAVFf1pEzqAbA2SQ2c',
    appId: '1:572486055461:ios:b44292202a9968575c71cc',
    messagingSenderId: '572486055461',
    projectId: 'presswave',
    storageBucket: 'presswave.appspot.com',
    iosBundleId: 'com.example.pressWave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZad41IxaykVFhgVXWr8AciOXDIHuQccU',
    appId: '1:572486055461:web:cde8a78e15a3b63f5c71cc',
    messagingSenderId: '572486055461',
    projectId: 'presswave',
    authDomain: 'presswave.firebaseapp.com',
    storageBucket: 'presswave.appspot.com',
    measurementId: 'G-G8NGQSGFW7',
  );
}
